- src/schemas/parseJsonSchema.js
There is a small bug here:
- https://github.com/MaterializeInc/datagen/blob/main/src/schemas/parseJsonSchema.js#L47
`Json` -> `JSON`
> fix small bug in json parser

- README.md
- datagen.js
- package-lock.json
- package.json
- src/jsonDataGenerator.js
- src/schemas/parseJsonSchema.js
- tests/datagen.test.js
- tests/datasize.json
Adding an option to the JSON schema to allow generating 1MB records.
The `benchmark: true` option in the `_mata` field, will generate a 1MB record. So if you have to generate 1GB of data, you run the command with the following options:
Closes #4
> Add data size option to json schemas

- src/jsonDataGenerator.js
- src/kafka/producer.js
- src/schemas/parseJsonSchema.js
- tests/schema.json
As a stepping stone to supporting relational data, I fixed Kafka record keys (json schema only). Now you can specify key like so:
```json
[
{
"_meta": {
"topic": "mz_datagen_comments",
"key": "email"
},
"id": "datatype.uuid",
"name": "internet.userName",
"email": "internet.exampleEmail",
"body": "lorem.paragraph",
"post_id": "datatype.uuid"
}
]
```
And the `email` will be used as the kafka record key:
```
✔  Record sent to Kafka topic: mz_datagen_comments  
key: Dorris87@example.org
value:
{"id":"a0bf7ce4-24b7-49e1-bc08-7f4d9d61a75f","name":"Coty91","email":"Dorris87@example.org","body":"Et cum cum perspiciatis inventore atque quis animi. Explicabo eos ea. Dolorem praesentium reprehenderit. Accusantium voluptates delectus nam earum minus pariatur soluta. Omnis recusandae quaerat placeat. …
```
> send user specified record keys to kafka

- src/kafka/createTopic.js
- src/kafka/producer.js
Managed to track down the topic creation problem. It looks like the default replication factor on confluent is `3` so if we try to use `1` the creation fails.
It also fails if we leave out the replication factor as the KafkaJS lib sets the value to `-1` by default which does not seem to do the trick.
As a fix, I'm using the `describeCluster` and `describeConfigs` methods to get the default replication factor and use it in the create topic call.
Closes #9
> Fix topic creation problem

- README.md
- datagen.js
- package-lock.json
- package.json
- src/jsonDataGenerator.js
- src/schemas/parseAvroSchema.js
- src/schemas/parseJsonSchema.js
- src/schemas/parseSqlSchema.js
- tests/datagen.test.js
This PR does mainly two things:
- Removes the `--schema-format` flag, it now detects the format based on the schema file extension, eg. `.sql, .json, .avcs`
- Updates the schema parsers so that each parser produces a JSON schema which is then passed to the Kafka producer
Ground work for the #1 issue and #17 PR
> Parsers to json

- .github/workflows/release.yml
Adding a release workflow to publish the package to npmjs.org on tag.
**Before we merge this, we need to add a `NPM_TOKEN` secret.**
> Add npmjs release workflow

- src/schemas/generateMegaRecord.js
- tests/schema.json
- tests/schema.sql
Adding an option to allow users to specify the faker properties options, eg:
```
faker.datatype.number(options: number | {
max: number,
min: number,
precision: number
} = 99999): number
```
There are some edge cases like dates, where this still needs to be improved, but it should cover what's mentioned in #39 
Closes #39
> Add faker data properties

- src/kafka/producer.js
KafkaJS only allows strings as kafka keys, so we have to cast to string.
https://github.com/tulios/kafkajs/issues/1544
> Cast kafka record key to string

- README.md
- src/dataGenerator.js
- src/schemas/generateMegaRecord.js
- tests/iterationIndex.json
To simulate auto incrementing primary keys, you can use the `iteration.index` variable in the schema.
This is particularly useful when you want to generate a small set of records with sequence of IDs, for example 1000 records with IDs from 1 to 1000:
```json
[
{
"_meta": {
"topic": "mz_datagen_users"
},
"id": "iteration.index",
"name": "internet.userName",
}
]
```
Example:
```
datagen -s tests/iterationIndex.json -dr true -f json -n 1000
```
This does not work particularly well with the relational data implementation, but it is mainly intended to be used with single schemas, eg. the Storage utilization test task.
N/A
> Add Iternation index option

- src/schemas/generateMegaRecord.js
- tests/schema.json
See 
- https://github.com/MaterializeInc/datagen/issues/53
closes https://github.com/MaterializeInc/datagen/issues/53
> Improve relationship declaration

- datagen.js
- package-lock.json
- package.json
- src/dataGenerator.js
- src/kafka/cleanKafka.js
delete topics and schema subjects using the `--clean` option
closes https://github.com/MaterializeInc/datagen/issues/50
> clean topics and schema subjects datagen creates

- .github/workflows/integration.yaml
- datagen.js
- src/dataGenerator.js
- src/kafka/cleanKafka.js
- src/kafka/createTopic.js
- src/kafka/producer.js
Taking the time to improve a couple of things:
- Adding a `--prefix|-p` flag to allow the usage of topic prefixes in order to avoid name collision.
- Refactored the code so that we only create 1 Kafka producer and use it across iterations
- Adding tests for the `--clean` flag.
Closes #61 
Closes #54
> Add topic prefix flag

- datagen.ts
Fixing the bug noticed during the weekly demo
N/A
> Fix infinite loop problem

- examples/ecommerce.json
- examples/ecommerce.md
just a small update to the e-commerce tutorial
- remove step to drop default cluster replica (not really relevant)
- added some query output
> Small e-commerce tutorial update

- src/dataGenerator.ts
- src/formats/avroFormat.ts
We lost the ability to see output avro schema when debugging a dry run. This happened because creating an instance of the AvroFormat class requires creating a schema registry client (which shouldn't happen on dry run). However, we don't actually need to create a schema registry client in order to see the what avro schemas would be produced with `--format avro`. All that is needed is one instance of a "megaRecord". We then use the @types/avro library to generate avro schema from the record.
To bring back this functionality of debugging output avro schema for a dry run, I made the `getAvroSchemas(megaRecord)` method static and call it during dry run on the first iteration in `dataGenerator`.
> Show debug output for avro schemas during dry run

- .env.example
- README.md
- src/kafka/kafkaConfig.ts
Adding support for mutual TLS authentication.
The user needs to set the following env vars:
```
SSL_CA_LOCATION=
SSL_CERT_LOCATION=
SSL_KEY_LOCATION=
```
We will have the following precedence: 
- If SASL env details are set, we will default to that
- Next in order will be TLS details
- Finally, if none are set we will default to no auth, eg. locally running Kafka
Closes #69
> Add mutual TLS authentication support

- .github/workflows/integration.yaml
- datagen.ts
- docker-compose.yaml
- package-lock.json
- src/kafka/cleanKafka.ts
- tests/datagen.test.ts
Switching the Kafka + CSR + Zookeeper containers to Redpanda.
Adding a path ignore for the `.md`, `.txt` files, and `examples` directory.
Not 100% sure if there will be any actual benefits of switching to the image caching suggestion as we only have the Redpanda image that will be pulled and we need to make sure that the datagen image is built fresh on every run to prevent some weird results. Open to suggestions!
Closes #87
> Switch tests to redpanda

- src/schemas/generateMegaRecord.ts
I translate Date objects generated by Faker to ISO 8601 formatted string to make it easy to output Avro formatted records that contain dates.
closes #68
> translate dates to strings for easy avro output

- src/schemas/parseAvroSchema.ts
- tests/complex-schema.avsc
- tests/datagen.test.ts
[Fix Bug 95 ](https://github.com/MaterializeInc/datagen/issues/95)
[Bug 95](https://github.com/MaterializeInc/datagen/issues/95)
> [BUG-95]: Fix parseAvroSchema for record type fields

- .env.example
- README.md
- datagen.ts
- examples/README.md
- examples/webhook/.env.example
- examples/webhook/README.md
- examples/webhook/sensors.json
- src/dataGenerator.ts
- src/webhook/webhookConfig.ts
- src/webhookDataGenerator.ts
- tests/datagen.test.ts
Adding webhook as a destination.
Currently, this works with basic authentication.
N/A
> Add webhook destniation

- src/kafkaDataGenerator.ts
- src/utils/recordSize.ts
- src/webhookDataGenerator.ts
Adding the `--record-size` option to the webhook destination.
N/A
> Add recordSize option to Webhooks

- .github/workflows/integration.yaml
- src/kafkaDataGenerator.ts
- src/postgres/createTables.ts
- src/postgresDataGenerator.ts
- src/schemas/generateMegaRecord.ts
- src/webhookDataGenerator.ts
- tests/datagen.test.ts
This PR fixes a couple of things:
- Fixed Kafka dry runs
- Abstracted the record payload size logic for all destinations
- Implement the `--record-size` flag for Postgres destinations 
N/A
> Refactor recordsize logic

- datagen.ts
- package-lock.json
- package.json
Update dependencies and version to v0.4.0 so we can cut a new release with the `webhook` format and the latest fixes.
> Update version to v0.4.0

- .env.example
- .github/workflows/integration.yaml
- README.md
- datagen.ts
- docker-compose.yaml
- package-lock.json
- package.json
- src/dataGenerator.ts
- src/mysql/createTablesMySQL.ts
- src/mysql/mysqlConfig.ts
- src/mysqlDataGenerator.ts
- src/schemas/parseSqlSchema.ts
- tests/datagen.test.ts
- tests/mysql-products.sql
- tests/mysql-schema.sql
Adding MySQL as a destination. This is going to be particularly useful with the new Materialize MySQL source.
Closes #113
> My sql destination

- datagen.ts
- package.json
Bump [faker](https://fakerjs.dev/api/) to the latest version, 8.4.1.
> bump faker version

- examples/README.md
- examples/kubernetes/README.md
- examples/kubernetes/datagen.yaml
- examples/kubernetes/redpanda.yaml
Adding a simple example on how to deploy datagen to Kubernetes alongside Redpanda.
> Add datagen Kubernetes guide
